### ISSUE TITLE
Proposal: Use real Clausen functions instead of complex Polylogarithms

### ISSUE THREAD

**Issue by Expander** [bastikr/CollectiveSpins.jl#27]
Dear CollectiveSpins developers,

I've noticed that in the function `Omega_k_chain` the following expression is calculated:
$$\Re(\text{Li}_3(e^{i(k_0+k)a}) + \text{Li}_3(e^{i(k_0-k)a}) - ik_0a[\text{Li}_2(e^{i(k_0+k)a}) + \text{Li}_2(e^{i(k_0-k)a})])$$
This expression uses (time-costly) complex polylogarithms. However, the result is purely real. I believe this expression can be expressed in terms of simpler real [Clausen functions](https://en.wikipedia.org/wiki/Clausen_function#Relation_to_the_polylogarithm), due to the following relations:
$$\Re[\text{Li}_3(e^{i\theta})] = \text{Cl}_3(\theta),\qquad\Im[\text{Li}_2(e^{i\theta})] = \text{Cl}_2(\theta)$$
Using these relations I believe the first expression can be written as:
$$\text{Cl}_3[(k_0+k)a] + \text{Cl}_3[(k_0-k)a] + k_0a(\text{Cl}_2[(k_0+k)a] + \text{Cl}_2[(k_0-k)a])$$
which can be significantly faster when a fast implementation of the Clausen functions is used.

In Julia one could use the package [ClausenFunctions.jl](https://juliahub.com/ui/Packages/ClausenFunctions/1a5QN/1.11.0) which provide very fast implementations of $\text{Cl}_2$ and $\text{Cl}_3$:
~~~.jl
using ClausenFunctions
cl2(1.0)
cl3(1.0)
~~~
Best regards
Alexander Voigt

**Comment by david-pl** [comment]
Hi Alexander,

thanks for pointing that out! I think you're right, at least tests pass locally if I switch things the way you suggested. Now I'm just waiting for CI to pass in #28. The next version of CollectiveSpins should include this then.

Cheers,
David

**Comment by Expander** [comment]
Hi David,

great! Thanks for considering this change!

Best regards
Alexander

(I think we can close this issue now.)

**Comment by david-pl** [comment]
It's now available with the new version of CollectiveSpins. FYI, also @taylorpatti
